Javascript/Prakash_helloworld.js

create hello world program

---

BubbleSort.c

Bubble sorting done in c programming language with dynamic array implementation

Bubble sort in c

---

C/KN_BubbleSort.c

Added KN_BubbleSort.c

---

Python/for-loop.py
Python/hello-world.py
Python/if-else.py
Python/insert-to-array.py
Python/odd-even.py
Python/palindrome.py
Python/square-num.py
Python/sum-of-digits-number.py
Python/sum-two-numbers.py
Python/uppercase.py

Python programs for listed operations

added all programs for python

---

Javascript/wahidari_change_letter_to_uppercase.js
Javascript/wahidari_check_number_is_odd_or_even.js
Javascript/wahidari_check_palindrome.js
Javascript/wahidari_find_square_of_number.js

add cek number is odd or even and find square of number in javascript

add javascript solutions

---

Simple calculator in python

Please merge this with approval commented as hactoberfest-accepted
As per the ne update from hacktober fest 2020

Create Simple calculator in python

---

shravaniparaswar_mergesort.C

Merge sort algorithm using array

Tried merge sort algorithm

---

C/Bibekdhkl-Hello-Program.c

In this C hello program, unlike other programs I have described all the basic concepts of tags to be it more beginner-friendly.

Created hello program in C with comments

---

Cpp/Bibekdhkl-Helloworld.cpp
Javascript/Bibekdhkl-Helloworld.js

Added **C++** and **JS** Hello World Program in an understandable way to beginners by using comments.
**Happy Coding**

Added C++ and JS Hello World Program

---

Python/randika97_BubbleSort.py

added bubble sort using python

added bubble sort using python

---

Python/BubbleSort.py

I implemented the bubble sort algorithm using python

implemented bubble_sort using python

---

C/TharushaGunasekara_sum2num.c

Tharusha gunasekara

---

C++/imakshat47_complexSorting copy.cpp
C++/imakshat47_complexSorting.cpp
C++/imakshat47_mapsQuery.cpp
C++/imakshat47_maxElement.cpp
C++/imakshat47_stlSets.cpp
C++/imakshat47_vectorDynamicErase.cpp
C++/imakshat47_vectorLowerBound.cpp
C++/imakshat47_vectorSort.cpp
Cpp/JollyJumper.cpp
Cpp/findMinDiff.cpp
Cpp/imakshat47_complexSorting copy.cpp
Cpp/imakshat47_complexSorting.cpp
Cpp/imakshat47_mapsQuery.cpp
Cpp/imakshat47_maxElement.cpp
Cpp/imakshat47_stlSets.cpp
Cpp/imakshat47_vectorDynamicErase.cpp
Cpp/imakshat47_vectorLowerBound.cpp
Cpp/imakshat47_vectorSort.cpp
Cpp/maxElement_imakshat47.cpp
Cpp/removeSort.cpp
Cpp/sorting_imakshat47.cpp
Cpp/vectorErase_imakshat47.cpp
Cpp/vectorSort_imakshat47.cpp
Cpp/xorArray.cpp
Python/Chacha!!OChacha.py
Python/JadooAndDNATranscription.py
Python/JadooHatesNumbers.py
Python/JadooVsKoba.py
Python/ReasonsWhy.py

Added some new program to repo

Updated new programs to repo

---

C/Pointer_Arithmetic_Sum.c

You Can Find Sum of Two Array Using Pointer in C language

Sum of Array Using Pointer Arithmetic

---

Go/SumTwoNumbers.go

This is a go program to sum two integers

[Go] Create program to Sum Two Numbers

---

Go/bubble sort

Solving the bubble sorting problem

Create bubble sort

---

Ruby/bubble_sort.rb
Ruby/bucket_sort.rb
Ruby/insertion_sort.rb

Bubble, bucket and insertion sorting

Ruby sorting scripts

---

JAVA/lihamfx_HelloWorld.java

Write hello world program with java

Create hello world

---

C/binarysearch_iterative.c

Hey, Added a iterative method of binary search in C. Please accept my PR and help me contribute open source. Thank you :)

added binary search program

---

Javascript/remove_duplicates.js
Javascript/selection_sort.js

created a function that sort an array of numbers which return the array of numbers ascendingly.

added selection sort using javascript

---

Go/Palindrome Tester

Solution for: Write a program to test whether the string is palindorme or not.

Create Palindrome Tester in Go

---

Javascript/ankit_cube.js

Get a value from user rather than a hard coded number

Get a value from user

---

C/DipakGautam_PallindromeOrNot.c

Hello there Bigyan ji,
I added a program to check any entered string is Palindrome or not in C.
Please have a look and merge it if you like it.
Thanks for this initiation and platform to be a part of hacktoberfest2020.
Thanks again!!

WAP to check any string is Palindrome or not

---

DIVISIBLE2.CPP

ADDED A PROGRAM TO CHECK DIVISIBILITY BY 2

 ADDED A PROGRAM TO CHECK DIVISIBILITY BY 2

---

C++/Queue.cpp

Added Implementation of Queue data structure using array in C++. Happy Learning!

Queue-Array

---

Python/AayushKumar_binarySearch .py

Adding Binary-Search implemented in Python

---

niharika_square.CPP

ADDED A PROGRAM TO FIND SQUARE

 ADDED A PROGRAM TO FIND SQUARE

---

C++/overloadingNewDelete.cpp

Operator overloading of new and delete in C

Added OverloadingNewDeleteoperator in C

---

C++/HeapSort.cpp

Hello there,
I added Heap sort to repository.
Hope you like it.

Added HeapSort.cpp

---

C++/GamerNishant_RadixSort.cpp.cpp

Adding Radix Sort to cpp folder.

Adding Radix Sort

---

C++/OverloadingComma.cpp

Added OverloadingComma.c

---

Dart/m-hamzashakeel.dart

Added basics operations like Addition, Subtractions, Multiplication and Division in `Dart`
Please labelled it as `hacktoberfest-accepted` thanks 👍

Basic Arthematics in Dart

---

JAVA/yugrajani_Uppercase.java

Program to convert the given input string to uppercase using inbuilt function.
Appropriate comments at each and every step of program added for beginners.
Instructions to compile and run the program:
Step 1 - Compilation: 'javac yugrajani_Uppercase.java'
Step 2 - Execution: 'java Uppercase'
Step 3 - Provide appropriate input and observe the output

Added the program 'yugrajani_Uppercase.java' to convert input string to Uppercase in JAVA

---

JAVA/sum_of_n_natural_number.java

sum of n natural number java program

sum of n natural number

---

Python/ZahraShahid_InsertionSort.py

A simple code to sort an array in python.

Insertion Sort by Zahra Sahahid

---

JAVA/sorting-programs/BubbleSort.java
JAVA/sorting-programs/InsertionSort.java
JAVA/sorting-programs/QuickSort.java
JAVA/sorting-programs/SelectionSort.java
JAVA/sorting-programs/readme.md

Hi,
Happy to contribute to this project.
I added sorting programs and soon like to contribute more such programs.
Hope to contribute more to open source. Thanks for the quick project.
Thanks

Java sorting programs stated in main README.md

---

Data_Structures/CirularLinkedList.java
Data_Structures/LinkedList.java
Data_Structures/Stack.cpp
Data_Structures/StackLL.cpp
Data_Structures/TreeArray.cpp
Data_Structures/XORlinkedList.cpp
Data_Structures/binary_tree.java
Data_Structures/binary_tree_using_array.java
Data_Structures/doublyLinkedList.java
Data_Structures/hashmap_imp.java
Data_Structures/linked_lists.cpp
Data_Structures/nth_from_last_LL.cpp

Data structures implementation in Java has been added.
=> LinkedList
=> Queue
=> Stack
=> Tree
=> HashMap

Added Data Structures

---

C++/PranavPatel_Reverse_words_in_String.cpp

Added program is a LeetCode problem 151.

Added the program 'PranavPatel_Reverse_words_in_String.cpp'

---

C/stack.c

Added stack.c

---

.idea/.gitignore
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
Hacktoberfest-Simple-Practice-Programmes.iml
JAVA/Gajendra_CustomStackImplementation.java

Hey there, 
i have added a custom class that implement all the Stack features.

Added CustomStackClass in java

---

C++/Dimas-Saputra-Me_CheckPalindromeInteger.cpp

Added Check Palindrome Integer in C++ Language.
You can use string input by changing datatype of "numberDigits" variable.

Added Check Palindrome Integer C++

---

JAVA/Xhiel23_PrimeNumbers.java

Check if a number is prime in Java

Add primeNumbers.java

---

Cpp/Imakshat47_binary2DecimalBasic.cpp
Cpp/Imakshat47_binary2DecimalUsingInBuildFun.cpp
Cpp/Imakshat47_binary2DecimalUsingString.cpp
Cpp/Imakshat47_binary2Octal.cpp
Cpp/Imakshat47_decimal2OctalBasic.cpp
Cpp/Imakshat47_decimal2OctalFormula.cpp
Cpp/Imakshat47_decimal2binaryBasicArray.cpp
Cpp/Imakshat47_decimal2binaryBasicVoid.cpp
Cpp/Imakshat47_decimal2binaryUsingBitwise.cpp
Cpp/Imakshat47_octal2binary.cpp

> ### C++ Maths Number Conversion Programs Added!

Updates: C++ Maths Number Conversion Programs

---

C++/graph.cpp

created graph.cpp

---

C++/string_palindrome.cpp

Added Program to check if string is Palindrome with the help of STL in C++.

Added Program to check if string is Palindrome

---

Python/sudokusolver.py

Created sudoku solver in python

Added: sudokusolver.py

---

Javascript/mitpancholi_octal_to_binary.js

octal_to_binary

---

Python/torrent_link_finder.py

Added Magnet Link Scraper built with Python

Torrent Magnet Link Finder built with Python

---

Python/binary_search.py

Added searching feature in python

---

Data_Structures/queueWithLL.cpp
Data_Structures/stackWithLL.cpp

added stack implementation with linked lists

---

JAVA/karprekar.java

karprekar number program by nandini agarwal

karprekar number java program

---

C/FibonacciNumbers.c
C/binary2DecimalBasic.c
C/decimal2OctalBasic.c
C/decimal2OctalFormula.c
C/decimal2binaryBasicVoid.c
C/decimal2binaryUsingBitwise.c
C/octal2binary.c

Updates: More Programs Added

---

Python/sujanp100_helloworld.py

Added: helloworld.py

---

Python/add_numbers.py

hey there,
This is a very simple python program which when runs it asked user to input two integer numbers and then it adds the number then display it in screen.
regards,
github.com/callmebhawesh

Adding two number by taking input from the user

---

C++/arjitarora26_sumofnumbers.cpp

Added program for addition of two integers

Sum of numbers

---

C++/husinassegaff_GameofTwoStacks.cpp
C++/husinassegaff_HowManyIslands.cpp
C++/husinassegaff_InfixNotation.cpp

Hello
I have added three programs about how many islands, game of two stacks, and infix notation in c ++. maybe it can be approved so that I can contribute to your repository too
thank you!

Added three programs in c++ folder

---

PHP/FibonacciNumber.php
PHP/FlippingBits.php
PHP/Primality.php

Updates: Added Python and C++ Flip Bit, Primality and Fibonacci Number

---

Python/FibonacciNumber.py
Python/FlippingBits.py
Python/Primality.py

Updates: Added Python Flip Bit, Primality and Fibonacci Number Programs

---

Cpp/ritikasarkar18_replaceChars-recursion.cpp

Given an input string S and two characters c1 and c2, you need to replace every occurrence of character c1 with character c2 in the given string, recursively.

Added string recursion cpp file

---

Javascript/time.js

Added a digital clock that runs on the console in the same line.

clock added in JS

---

Javascript/hrishikesh_javascript_quicksort.js

@bigyanic A simple quick sort in Javascript implementation by Hrishikesh

Javascript Quick Sort by Hrishikesh

---

Javascript/server.js

Added an express server in Javascript

Web server added

---

JAVA/SquareRoot.java

A simple java program that checks the square root of a number.

Added SquareRoot.java

---

Python/jump_search.py

Created a new file called jump_search.py which includes an implementation of the jump search algorithm. The user inputs a sorted array and a number and the script returns the index of the given number.

Add jump search algorithm written in python

---

C++/simonlariz_DecimalToBinary.cpp

Addition of Decimal to Binary problem in c++

simonLariz DecimalToBinary Problem

---

C++/CountingSort/countingSort.h
C++/CountingSort/main.cpp

From [https://en.wikipedia.org/wiki/Counting_sort](url)
"In computer science, counting sort is an algorithm for sorting a collection of objects according to keys that are small integers; that is, it is an integer sorting algorithm. It operates by counting the number of objects that have each distinct key value, and using arithmetic on those counts to determine the positions of each key value in the output sequence. Its running time is linear in the number of items and the difference between the maximum and minimum key values, so it is only suitable for direct use in situations where the variation in keys is not significantly greater than the number of items"

Counting sort

---

C++/EulerMethod/eulerMethod.cpp
C++/EulerMethod/eulerMethod.h
C++/EulerMethod/main.cpp

[https://en.wikipedia.org/wiki/Euler_method](url)
"The Euler method (also called forward Euler method) is a first-order numerical procedure for solving ordinary differential equations (ODEs). It is the most basic explicit method for numerical integration of ordinary differential equations and is the simplest Runge–Kutta method."

Euler method

---

C++/BisectionMethod/bisectionMethod.cpp
C++/BisectionMethod/bisectionMethod.h
C++/BisectionMethod/main.cpp

[https://en.wikipedia.org/wiki/Bisection_method](url)
"In mathematics, the bisection method is a root-finding method that applies to any continuous functions for which one knows two values with opposite signs. The method consists of repeatedly bisecting the interval defined by these values and then selecting the subinterval in which the function changes sign, and therefore must contain a root. It is a very simple and robust method, but it is also relatively slow. Because of this, it is often used to obtain a rough approximation to a solution which is then used as a starting point for more rapidly converging methods. The method is also called the interval halving method".

Bisection method

---

Python/find_factorial.py
Python/primeNumber_checker.py

Python programme to find factorial of a number.

find_factorial created
